package DTO;

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

public class CompaniaSeguro  {

    private Integer id;  // t
    private String nombre;  // t

    public Integer get_id() {
        return this.id;
    }

    public void set_id(Integer id) {
        this.id = id;
    }

    public String get_nombre() {
        return this.nombre;
    }

    public void set_nombre(String nombre) {
        this.nombre = nombre;
    }
}