package DTO;

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

public class FichaMecanica  {

    private Integer id;  // t
    private String actividades;  // t
    private Integer ficha_conformidad_id;  // t
    private String repuestos;  // t

    public Integer get_id() {
        return this.id;
    }

    public void set_id(Integer id) {
        this.id = id;
    }

    public String get_actividades() {
        return this.actividades;
    }

    public void set_actividades(String actividades) {
        this.actividades = actividades;
    }

    public Integer get_ficha_conformidad_id() {
        return this.ficha_conformidad_id;
    }

    public void set_ficha_conformidad_id(Integer ficha_conformidad_id) {
        this.ficha_conformidad_id = ficha_conformidad_id;
    }

    public String get_repuestos() {
        return this.repuestos;
    }

    public void set_repuestos(String repuestos) {
        this.repuestos = repuestos;
    }
}