package DTO;

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

public class FichaConformidad  {

    private Integer id;  // t
    private String motivos_disconforme;  // t
    private Boolean firmada;  // t
    private Boolean firmada_conforme;  // t

    public Integer get_id() {
        return this.id;
    }

    public void set_id(Integer id) {
        this.id = id;
    }

    public String get_motivos_disconforme() {
        return this.motivos_disconforme;
    }

    public void set_motivos_disconforme(String motivos_disconforme) {
        this.motivos_disconforme = motivos_disconforme;
    }

    public Boolean get_firmada() {
        return this.firmada;
    }

    public void set_firmada(Boolean firmada) {
        this.firmada = firmada;
    }

    public Boolean get_firmada_conforme() {
        return this.firmada_conforme;
    }

    public void set_firmada_conforme(Boolean firmada_conforme) {
        this.firmada_conforme = firmada_conforme;
    }
}
