package DTO;

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

import java.sql.Time;
import java.time.LocalTime;

public class HorarioAtencion  {

    private Integer id;  // t
    private String dia_atencion;  // t
    private LocalTime hora_desde;  // t
    private LocalTime hora_hasta;  // t
    private Integer mecanico_id;  // t

    public Integer get_id() {
        return this.id;
    }

    public void set_id(Integer id) {
        this.id = id;
    }

    public String get_dia_atencion() {
        return this.dia_atencion;
    }

    public void set_dia_atencion(String dia_atencion) {
        this.dia_atencion = dia_atencion;
    }

    public LocalTime get_hora_desde() {
        return this.hora_desde;
    }

    public void set_hora_desde(LocalTime hora_desde) {
        this.hora_desde = hora_desde;
    }

    public LocalTime get_hora_hasta() {
        return this.hora_hasta;
    }

    public void set_hora_hasta(LocalTime hora_hasta) {
        this.hora_hasta = hora_hasta;
    }

    public Integer get_mecanico_id() {
        return this.mecanico_id;
    }

    public void set_mecanico_id(Integer mecanico_id) {
        this.mecanico_id = mecanico_id;
    }
}
