package DTO;

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

public class Mecanico  {

    private Integer id;  // t
    private String nombre;  // t
    private String telefono;  // t
    private String apellido;  // t
    private String tipo_documento;  // t
    private String documento;  // t

    public Integer get_id() {
        return this.id;
    }

    public void set_id(Integer id) {
        this.id = id;
    }

    public String get_nombre() {
        return this.nombre;
    }

    public void set_nombre(String nombre) {
        this.nombre = nombre;
    }

    public String get_telefono() {
        return this.telefono;
    }

    public void set_telefono(String telefono) {
        this.telefono = telefono;
    }

    public String get_apellido() {
        return this.apellido;
    }

    public void set_apellido(String apellido) {
        this.apellido = apellido;
    }

    public String get_tipo_documento() {
        return this.tipo_documento;
    }

    public void set_tipo_documento(String tipo_documento) {
        this.tipo_documento = tipo_documento;
    }

    public String get_documento() {
        return this.documento;
    }

    public void set_documento(String documento) {
        this.documento = documento;
    }
}